---
# file: main.yml
- name: clone svenv.nl-docker from github
  git:
    repo=https://github.com/svenvandescheur/svenv.nl-docker.git dest=/srv/svenv.nl-docker force=yes

- name: add tarsnap key to docker
  copy: content="{{ tarsnap }}" dest=/srv/svenv.nl-docker/files/root/tarsnap.key

- name: add environment file
  template: src=environment.j2 dest=/srv/svenv.nl-docker/files/etc/environment

- name: build image
  docker_image:
    path=/srv/svenv.nl-docker
    name=svenv/svenv.nl
    nocache=yes
    state=build

- name: start svenv/svenv.nl container
  docker:
    name: svenv.nl
    ports:
    - 80:80
    - 3306:3306
    image: svenv/svenv.nl
    docker_api_version: 1.18  # http://stackoverflow.com/questions/31459513
    state: restarted

- name: add svenv.nl upstart job
  template: src=svenv.nl.conf.j2 dest=/etc/init/svenv.nl.conf