---
# file: main.yml
- name: 'config ufw: allow http'
  ufw: rule=allow port=80 proto=tcp

- name: 'config ufw: allow ssl'
  ufw: rule=allow port=443 proto=tcp

- name: 'clone docker-svenv.nl-data from github'
  git: repo="https://github.com/svenvandescheur/docker-svenv.nl-data.git" dest="/srv/docker-svenv.nl-data/" force=yes

- name: 'add ssh key to docker-svenv.nl-data'
  copy: content="{{ id_rsa }}" dest=/srv/docker-svenv.nl-data/files/root/.ssh/id_rsa

- name: 'fix persmissions of ssh key'
  file: path="/srv/docker-svenv.nl-data/files/root/.ssh/id_rsa" mode=0600

- name: 'add tarsnap key to docker-svenv.nl-data'
  copy: content="{{ tarsnap_key }}" dest=/srv/docker-svenv.nl-data/files/srv/tarsnap/tarsnap.key

- name: 'make sure the /srv/docker-svenv.nl-data/files/srv/tarsnap/ directory exists'
  file: path=/srv/docker-svenv.nl-data/files/srv/tarsnap/ state=directory

- name: 'add tarsnap key to docker-svenv.nl-data'
  copy: content="{{ tarsnap_key }}" dest=/srv/docker-svenv.nl-data/files/srv/tarsnap/tarsnap.key

- name: 'make sure the /srv/docker-svenv.nl-data/files/etc/ssl/certs/ directory exists'
  file: path=/srv/docker-svenv.nl-data/files/etc/ssl/certs/ state=directory

- name: 'add ssl certificate'
  copy: content="{{ svenv_nl_crt }}" dest=/srv/docker-svenv.nl-data/files/etc/ssl/certs/svenv.nl.crt

- name: 'add ssl certificate keyfile'
  copy: content="{{ svenv_nl_key }}" dest=/srv/docker-svenv.nl-data/files/etc/ssl/certs/svenv.nl.key

- name: 'add dh params'
  copy: content="{{ dhparams_pem }}" dest=/srv/docker-svenv.nl-data/files/etc/ssl/certs/dhparams.pem

- name: 'make sure the /srv/docker-svenv.nl-data/files/srv/uwsgi/ directory exists'
  file: path=/srv/docker-svenv.nl-data/files/srv/uwsgi/ state=directory

- name: 'add Django secret key'
  copy: content="{{ key_txt }}" dest=/srv/docker-svenv.nl-data/files/srv/uwsgi/key.txt

- name: 'add Django database password'
  copy: content="{{ pw_txt }}" dest=/srv/docker-svenv.nl-data/files/srv/uwsgi/pw.txt

- name: 'build/start svenv.nl containers'
  docker_service: project_src=/srv/docker-svenv.nl-data/ state=present build=yes restarted=yes