---
# file: site.yml
- hosts: appservers
  gather_facts: False
  pre_tasks:
      - name: 'install python'
        raw: sudo apt-get -y install python
  roles:
    - common
    - appserver
    - vpnserver
    - muninnode
  vars_files:
    - roles/appserver/vars/keys.yml
    - roles/vpnserver/vars/keys.yml