---
# file: main.yml
- name: 'config ufw: allow munin'
  ufw: rule=allow port=4949 proto=tcp

- name: install munin-node
  apt: name=munin-node state=present

- name: 'config munin: add /etc/munin/munin-node.conf'
  template: src=munin-node.conf.j2 dest=/etc/munin/munin-node.conf

- name: 'reload munin-node service'
  service: name=munin-node state=started