---
# file: main.yml
- name: 'config ufw: allow openvpn'
  ufw: rule=allow port=1194 proto=udp

- name: 'clone vpn-docker-data from github'
  git: repo=https://github.com/svenvandescheur/docker-openvpn-data.git dest=/srv/docker-openvpn-data force=yes
  register: dockeropenvpndata

- name: 'remove pki.zip'
  file: path=/srv/docker-openvpn-data/files/etc/openvpn/pki.zip state=absent
  when: dockeropenvpndata.changed

- name: 'remove pki'
  file: path=/srv/docker-openvpn-data/files/etc/openvpn/pki state=absent
  when: dockeropenvpndata.changed

- name: 'decrypt pki.zip.gpg'
  shell: echo '{{ pki_folder_key }}' | gpg --passphrase-fd 0 pki.zip.gpg chdir=/srv/docker-openvpn-data/files/etc/openvpn/
  when: dockeropenvpndata.changed

- name: 'unzip pki.zip'
  shell: unzip pki.zip chdir=/srv/docker-openvpn-data/files/etc/openvpn/
  when: dockeropenvpndata.changed

- name: 'build/start openvpn containers'
  docker_service: project_src=/srv/docker-openvpn-data/ state=present build=yes restarted=yes
