---
# main.yml
- name: apt-get update
  apt: update_cache=yes

- name: install mailutils
  apt: name=mailutils state=present

- name: install unattended-upgrades
  apt: name=unattended-upgrades state=present

- name: config unattended-upgrades
  template: src=10periodic dest=/etc/apt/apt.conf.d/
  template: src=50unattended-upgrades dest=/etc/apt/apt.conf.d/

- name: install git
  apt: name=git state=present

- name: config git
  command: git config --global user.name "Sven van de Scheur"
  command: git config --global user.email svenvandescheur@gmail.com

- name: install fish
  apt: name=fish state=present

- name: download docker install script
  get_url:
    url=https://get.docker.com/ubuntu/
    dest=/tmp/install_docker.sh

- name: install docker
  command: /bin/bash /tmp/install_docker.sh
