---
# file: main.yml
- name: apt-get update
  apt: update_cache=yes

- name: install mailutils
  apt: name=mailutils state=present

- name: install unattended-upgrades
  apt: name=unattended-upgrades state=present

- name: config unattended-upgrades 1/2
  template: src=10periodic.j2 dest=/etc/apt/apt.conf.d/10periodic
- name: config unattended-upgrades 2/2
  template: src=50unattended-upgrades.j2 dest=/etc/apt/apt.conf.d/50unattended-upgrades

- name: install git
  apt: name=git state=present

- name: config git
  template: src=.gitconfig.j2 dest=/root/.gitconfig

- name: install fish
  apt: name=fish state=present

- name: config fish
  user: name=root shell=/usr/bin/fish

- name: install sl
  apt: name=sl state=present

- name: install figlet
  apt: name=figlet state=present

- name: configure update-motd 1/2
  template: src=00-header.j2 dest=/etc/update-motd.d/00-header

- name: configure update-motd 2/2
  template: src=10-help-text.j2 dest=/etc/update-motd.d/10-help-text

- name: check for docker installation
  command: docker -v
  register: docker_check
  changed_when: docker_check.stdout.find('Docker version') == -1

- name: download docker install script
  get_url: url=https://get.docker.com/ubuntu/ dest=/tmp/install_docker.sh
  when: docker_check.stdout.find('Docker version') == -1

- name: install docker
  command: /bin/bash /tmp/install_docker.sh
  when: docker_check.stdout.find('Docker version') == -1

- name: install python-pip
  apt: name=python-pip state=latest

- name: install docker-py
  pip: name=docker-py state=present