---
# file: main.yml
- name: clone svenv.nl-docker from github
  git:
    repo=https://github.com/svenvandescheur/svenv.nl-docker.git dest=/srv/svenv.nl-docker

- name: check or build image
  docker_image:
    path=/srv/svenv.nl-docker
    name=svenv/svenv.nl
    state=build

- name: start svenv/svenv.nl container
  docker:
    name: svenv.nl
    volumes:
    - /srv/svenv.nl-docker/data/var/lib/mysql/:/var/lib/mysql/
    - /srv/svenv.nl-docker/data/svenv.nl/svenv/media:/svenv.nl/svenv/media
    ports:
    - 80:80
    - 3306:3306
    image: svenv/svenv.nl
    docker_api_version: 1.18  # http://stackoverflow.com/questions/31459513